apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luxe-living-store
  labels:
    app: luxe-living-store
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: luxe-living.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: luxe-living-store
                port:
                  number: 8080
